### ISSUE TITLE
Exception: Unable to extract mountpoint

### ISSUE THREAD

**Issue by draand28** [tntmod54321/zdb-recover#1]
Hi! I tried your script but I keep receiving the following error:
`Starting...
Traceback (most recent call last):
  File "/mnt/Raid Z1/SMB1/Backup RAID PC 5x1TB/zdb_recover.py", line 169, in <module>
    main()
  File "/mnt/Raid Z1/SMB1/Backup RAID PC 5x1TB/zdb_recover.py", line 115, in main
    pointers, mntPoint, tsize = getObjBlkPointers(path)
  File "/mnt/Raid Z1/SMB1/Backup RAID PC 5x1TB/zdb_recover.py", line 34, in getObjBlkPointers
    path = pathParse(path)
  File "/mnt/Raid Z1/SMB1/Backup RAID PC 5x1TB/zdb_recover.py", line 21, in pathParse
    else: raise Exception('Unable to extract mountpoint')
Exception: Unable to extract mountpoint`

I should mention that I startet the py script with:
`python zdb_recover.py -i "/mnt/Raid Z1/SMB1/Backup RAID PC 5x1TB/facultate.rar" -o "/mnt/Raid Z1/SMB1/Backup RAID PC 5x1TB/facultate3.rar"`

**Comment by tntmod54321** [comment]
Hi, are you running this on the truenas install? it has to be run directly on the NAS (through web-ui truenas shell is fine) and not on a remote machine, since it uses a zfs debug tool to retrieve the damaged data.

**Comment by tntmod54321** [comment]
Re-reading this it doesn't seem to be an issue with my script, since the error is accessing the py file itself, I would verify that the path is correct, it can be kinda confusing, I would navigate the /mnt/ with the truenas shell and follow it to the directory where the file is to verify the path.

**Comment by tntmod54321** [comment]
Oh my bad I didn't properly read the error, I think this might be an issue with the spaces in the path name, I'll see about rewriting that portion.  
Unless you're not on Truenas, in which case try changing `isTruenas = True` to `False` in `zdb_recover.py`.

**Comment by tntmod54321** [comment]
Hi, I rewrote the code relating to paths, try running the new version on the NAS.

**Comment by draand28** [comment]
Hi! Yes, I was running it on truenas scale (linux) via the web-gui shell.

In the meantime I have changed the pool and dataset names to not include spaces, but the scripts exists when encountering an Input/Output error.  For example, "nvidia.rar" is an archive of 22GB, but your script and "dd" as well stop copying upon encountring an i/o error at 1.7GB. The file is not 100% corrupted. I have recovered more from it (9-10GB) using a windows program and SMB (https://www.roadkil.net/program.php?ProgramID=29).

So it doesn't do anything different from a simple `dd` on my part at least. I have also tried the normal zdb command from your reddit post but it throws a similar error, so I don't think your script is at fault, but zdb.

Anyway, right now I'll destroy the pool as I recovered most of the important data (95% of it wasn't corrupted at all, the other I partially recovered with roadkil's software). So probably I won't be able to test your script.

On the other hand, it works great on non-corrupted files, so again, I'm pretty sure that it's not your script at fault, but zdb.

Here's the new output:
`root@truenas[/mnt/meh/SMB1/Backup_raid5]# python zdb_recover.py -i /mnt/meh/SMB1/Backup_raid5/nvidia.rar -o /mnt/backup/nvidia10.rar
Starting...
failed to lookup dataset=meh path=/SMB1/Backup_raid5: No such file or directory
Traceback (most recent call last):
  File "/mnt/meh/SMB1/Backup_raid5/zdb_recover.py", line 169, in <module>
    main()
  File "/mnt/meh/SMB1/Backup_raid5/zdb_recover.py", line 115, in main
    pointers, mntPoint, tsize = getObjBlkPointers(path)
  File "/mnt/meh/SMB1/Backup_raid5/zdb_recover.py", line 47, in getObjBlkPointers
    if objStatus != None: raise Exception('Unexpected zdb -O command response')
Exception: Unexpected zdb -O command response
root@truenas[/mnt/meh/SMB1/Backup_raid5]# `

Also I have tripled check that the file is there, here's an output of "cp" to prove that:
`root@truenas[/mnt/meh/SMB1/Backup_raid5]# cp /mnt/meh/SMB1/Backup_raid5/nvidia.rar /mnt/backup/nvidia10.rar
cp: error reading '/mnt/meh/SMB1/Backup_raid5/nvidia.rar': Input/output error`

Anyway, thank you for your script! I'm sure it can be helpful for some people. Unfortunately, not for me.

**Comment by tntmod54321** [comment]
Bummer, thanks for the follow up!
